url: https://fedgeo.us
# baseurl: /fedgeo.us

# Site settings
title: FedGeoDay
year: 2019
email: osgeo@technocation.org
description: "Open Source Geospatial in the Federal Government"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
